### ISSUE TITLE
Cloud you guys also provide examples for c++?

### ISSUE THREAD

**Issue by haorenfsa** [AliyunContainerService/ack-ram-tool#158]
Hi team, thank you for providing this example for go. Our services use both go & c++. 
Cloud you guys also provide examples for c++?

**Comment by mozillazg** [comment]
@haorenfsa I added a new example for c++: https://github.com/AliyunContainerService/ack-ram-tool/tree/develop/examples/rrsa/cpp-sdk

**Comment by haorenfsa** [comment]
Thank you so much !
By the way, I've also finished some code to implement an AWS Credential Provider, so that AWS SDK user can use RRSA. Are you guys interested? I can open a PR if so

**Comment by haorenfsa** [comment]
out of topic:
> 话说看id是竹刚？ 好巧啊，我是少越，之前infra 天文组的 哈哈哈

**Comment by mozillazg** [comment]
> By the way, I've also finished some code to implement an AWS Credential Provider, so that AWS SDK user can use RRSA directly. Are you guys interested? I can open a PR if so

PR is welcome~
